### ISSUE TITLE
can not install tabtab zsh

### ISSUE THREAD

**Issue by rdbox** [mklabs/tabtab#45]
Here is my error in the logs

```
 tabtab:commands User shell undefined not supported, skipping completion install +0ms
```
os windows 7

what should I do ?

**Comment by mklabs** [comment]
Hi @rdbox I don't really know. I would recommend not trying to use tabtab on Windows, at least for the moment.

What is your shell ? Are you using Bash on Windows ? (with linux sub-system ? But I believe it's only available on windows 10) Tabtab doesn't support Windows out of the box and I didn't tested it with cygwin.

**Comment by rdbox** [comment]
Yes, I'm using the console from cygwin
I have win 7 now

**Comment by mklabs** [comment]
Thanks @rdbox for the anwsers. Yeah, I didn't tested tabtab on cygwin at all, so I'm afraid you can't use it on Win 7. I'm sorry for that. Maybe one day if we can get it through.

I'm closing the issue now. I'll reopen when appropriate if and when we choose to support cygwin as well.
