### ISSUE TITLE
This package is bloated

### ISSUE THREAD

**Issue by fabiospampinato** [mklabs/tabtab#48]
I've been making CLI apps with [Caporal.js](https://github.com/mattallty/Caporal.js) for a while, and they start-up slowly and are bloated. Most of the bloat comes from this package, you guys are importing about 8MB from [Inquirer](https://github.com/SBoudrias/Inquirer.js) just for asking which shell to use.

Inquirer comes with all sorts of advanced prompts which this package isn't using at all, there must be a faster/less-bloated way of doing the same thing.

**Comment by alcuadrado** [comment]
Just wanted to point out that [Enquirer](https://github.com/enquirer/enquirer) is a blazing fast replacement of Inqurier. Not exactly a drop-in replacement, but almost.

**Comment by fabiospampinato** [comment]
@alcuadrado I don't think the performance of Inquirer is the problem here. This package doesn't need this thing Enquirer provides:

<img width="374" alt="screen shot 2019-03-01 at 17 13 10" src="https://user-images.githubusercontent.com/1812093/53650690-623bb180-3c45-11e9-9952-45342eb1a6f5.png">

**Comment by alcuadrado** [comment]
You are right, but moving to enquirer should be easy and would make things better.

I'm not sure how maintained is this package though. This issue is still open: https://github.com/mklabs/tabtab/issues/46

**Comment by fabiospampinato** [comment]
@mklabs why did you close this?
